"use client";

import {
  ChangeEvent,
  DragEvent,
  useRef,
  useState,
} from "react";

const API_URL =
  process.env.NEXT_PUBLIC_API_URL ||
  "http://127.0.0.1:8000";

type ExplanationEvidence = {
  base_probability: number;
  max_positive_influence: number;
  max_negative_influence: number;
  mean_absolute_influence: number;
};

type Prediction = {
  label: string;
  confidence: number;
  probability_ai_generated: number;
  threshold: number;
  model: string;
  explanation_image?: string;
  explanation_method?: string;
  explanation_evidence?: ExplanationEvidence;
  explanation_text?: string;
};

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null);

  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [prediction, setPrediction] =
    useState<Prediction | null>(null);

  const [dragging, setDragging] =
    useState(false);
  const [loading, setLoading] =
    useState(false);
  const [error, setError] =
    useState<string | null>(null);

  function selectFile(
    selectedFile: File | undefined
  ) {
    if (!selectedFile) {
      return;
    }

    if (!selectedFile.type.startsWith("image/")) {
      setError(
        "Please select a valid image file."
      );
      return;
    }

    setFile(selectedFile);
    setPrediction(null);
    setError(null);

    const url =
      URL.createObjectURL(selectedFile);

    setPreview(url);
  }

  function handleFileChange(
    event: ChangeEvent<HTMLInputElement>
  ) {
    selectFile(event.target.files?.[0]);
  }

  function handleDrop(
    event: DragEvent<HTMLDivElement>
  ) {
    event.preventDefault();
    setDragging(false);

    selectFile(
      event.dataTransfer.files?.[0]
    );
  }

  async function analyzeImage() {
    if (!file) {
      return;
    }

    setLoading(true);
    setError(null);

    const formData = new FormData();
    formData.append("file", file);

    try {
      const response = await fetch(
        `${API_URL}/predict`,
        {
          method: "POST",
          body: formData,
        }
      );

      const data = await response.json();

      if (!response.ok) {
        throw new Error(
          data.detail ||
            "Prediction failed."
        );
      }

      setPrediction(data);
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Unable to connect to SignalScope."
      );
    } finally {
      setLoading(false);
    }
  }

  function clearImage() {
    if (preview) {
      URL.revokeObjectURL(preview);
    }

    setFile(null);
    setPreview(null);
    setPrediction(null);
    setError(null);

    if (inputRef.current) {
      inputRef.current.value = "";
    }
  }

  const isAi =
    prediction?.label ===
    "Likely AI-Generated";

  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <div className="mx-auto flex min-h-screen w-full max-w-6xl flex-col px-6 py-8 md:px-10 lg:px-12">
        <header className="flex items-center justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.28em] text-cyan-400">
              SignalScope
            </p>

            <h1 className="mt-2 text-2xl font-semibold tracking-tight md:text-3xl">
              AI-generated image detection
            </h1>
          </div>

          <div className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs text-slate-300">
            CLIP + FFT
          </div>
        </header>

        <section className="grid flex-1 gap-8 py-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">
          <div>
            <div className="max-w-2xl">
              <p className="text-sm font-medium text-cyan-400">
                Generalization-first detection
              </p>

              <h2 className="mt-4 text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">
                Understand whether an image is
                likely real or AI-generated.
              </h2>

              <p className="mt-5 max-w-xl text-base leading-7 text-slate-400">
                Upload an image and SignalScope
                analyzes semantic and frequency
                evidence to estimate the likelihood
                that it was generated by AI.
              </p>
            </div>

            <div
              onDragOver={(event) => {
                event.preventDefault();
                setDragging(true);
              }}
              onDragLeave={() =>
                setDragging(false)
              }
              onDrop={handleDrop}
              onClick={() =>
                inputRef.current?.click()
              }
              className={`mt-10 cursor-pointer rounded-3xl border border-dashed p-8 transition ${
                dragging
                  ? "border-cyan-400 bg-cyan-400/10"
                  : "border-white/15 bg-white/[0.03] hover:border-white/30 hover:bg-white/[0.05]"
              }`}
            >
              <input
                ref={inputRef}
                type="file"
                accept="image/jpeg,image/png,image/webp,image/bmp"
                className="hidden"
                onChange={handleFileChange}
              />

              <div className="text-center">
                <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-white/10 text-2xl">
                  ↑
                </div>

                <h3 className="mt-5 text-lg font-medium">
                  Drop an image here
                </h3>

                <p className="mt-2 text-sm text-slate-500">
                  or click to browse
                </p>

                <p className="mt-5 text-xs text-slate-600">
                  JPEG, PNG, WebP, or BMP
                </p>
              </div>
            </div>

            {file && (
              <div className="mt-4 flex items-center justify-between rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3">
                <div className="min-w-0">
                  <p className="truncate text-sm font-medium">
                    {file.name}
                  </p>

                  <p className="mt-1 text-xs text-slate-500">
                    {(file.size / 1024 / 1024).toFixed(
                      2
                    )}{" "}
                    MB
                  </p>
                </div>

                <button
                  type="button"
                  onClick={(event) => {
                    event.stopPropagation();
                    clearImage();
                  }}
                  className="ml-4 rounded-lg px-3 py-2 text-xs text-slate-400 transition hover:bg-white/10 hover:text-white"
                >
                  Remove
                </button>
              </div>
            )}

            {error && (
              <div className="mt-4 rounded-2xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-300">
                {error}
              </div>
            )}

            <button
              type="button"
              disabled={!file || loading}
              onClick={analyzeImage}
              className="mt-6 w-full rounded-2xl bg-cyan-400 px-5 py-4 text-sm font-semibold text-slate-950 transition hover:bg-cyan-300 disabled:cursor-not-allowed disabled:opacity-40"
            >
              {loading
                ? "Analyzing image..."
                : "Analyze Image"}
            </button>

            {loading && (
              <p className="mt-3 text-center text-xs text-slate-500">
                Running the detector and generating model evidence...
              </p>
            )}
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5 shadow-2xl">
            <div className="overflow-hidden rounded-2xl bg-black/30">
              {preview ? (
                <img
                  src={preview}
                  alt="Selected image"
                  className="aspect-square w-full object-contain"
                />
              ) : (
                <div className="flex aspect-square items-center justify-center px-8 text-center">
                  <div>
                    <p className="text-sm font-medium text-slate-300">
                      Image preview
                    </p>

                    <p className="mt-2 text-xs leading-5 text-slate-600">
                      Your selected image will
                      appear here before analysis.
                    </p>
                  </div>
                </div>
              )}
            </div>

            <div className="mt-5 rounded-2xl border border-white/10 bg-black/20 p-5">
              {prediction ? (
                <>
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <p className="text-xs uppercase tracking-[0.2em] text-slate-500">
                        Result
                      </p>

                      <h3
                        className={`mt-2 text-2xl font-semibold ${
                          isAi
                            ? "text-rose-300"
                            : "text-emerald-300"
                        }`}
                      >
                        {prediction.label}
                      </h3>
                    </div>

                    <div className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-400">
                      {prediction.model}
                    </div>
                  </div>

                  <div className="mt-6">
                    <div className="flex items-end justify-between">
                      <span className="text-sm text-slate-400">
                        P(AI-generated)
                      </span>

                      <span className="text-3xl font-semibold">
                        {(
                          prediction.probability_ai_generated *
                          100
                        ).toFixed(2)}
                        %
                      </span>
                    </div>

                    <div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10">
                      <div
                        className={`h-full rounded-full transition-all ${
                          isAi
                            ? "bg-rose-400"
                            : "bg-emerald-400"
                        }`}
                        style={{
                          width: `${
                            prediction.probability_ai_generated *
                            100
                          }%`,
                        }}
                      />
                    </div>
                  </div>

                  <div className="mt-5 grid grid-cols-2 gap-3">
                    <div className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
                      <p className="text-xs text-slate-500">
                        Decision threshold
                      </p>

                      <p className="mt-1 text-sm font-medium">
                        {(
                          prediction.threshold *
                          100
                        ).toFixed(2)}
                        %
                      </p>
                    </div>

                    <div className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
                      <p className="text-xs text-slate-500">
                        Confidence
                      </p>

                      <p className="mt-1 text-sm font-medium">
                        {(
                          prediction.confidence *
                          100
                        ).toFixed(2)}
                        %
                      </p>
                    </div>
                  </div>

                  {prediction.explanation_image && (
                    <div className="mt-6 border-t border-white/10 pt-6">
                      <div>
                        <p className="text-xs uppercase tracking-[0.2em] text-slate-500">
                          Model Evidence
                        </p>

                        <h4 className="mt-2 text-sm font-medium text-slate-200">
                          Where the prediction changed most
                        </h4>
                      </div>

                      <div className="mt-4 grid grid-cols-2 gap-3">
                        <div>
                          <p className="mb-2 text-[11px] uppercase tracking-wider text-slate-500">
                            Original
                          </p>

                          <div className="overflow-hidden rounded-xl border border-white/10 bg-black/30">
                            {preview && (
                              <img
                                src={preview}
                                alt="Original image"
                                className="aspect-square w-full object-cover"
                              />
                            )}
                          </div>
                        </div>

                        <div>
                          <p className="mb-2 text-[11px] uppercase tracking-wider text-slate-500">
                            Evidence
                          </p>

                          <div className="overflow-hidden rounded-xl border border-white/10 bg-black/30">
                            <img
                              src={prediction.explanation_image}
                              alt="SignalScope model evidence overlay"
                              className="aspect-square w-full object-cover"
                            />
                          </div>
                        </div>
                      </div>

                      <div className="mt-3 flex flex-wrap items-center justify-center gap-x-5 gap-y-2 text-[11px] text-slate-400">
                        <span className="flex items-center gap-1.5">
                          <span className="h-2.5 w-2.5 rounded-full bg-rose-400" />
                          Supports AI-generated
                        </span>

                        <span className="flex items-center gap-1.5">
                          <span className="h-2.5 w-2.5 rounded-full bg-blue-400" />
                          Opposes AI-generated
                        </span>
                      </div>

                      {prediction.explanation_text && (
                        <p className="mt-4 text-xs leading-5 text-slate-400">
                          {prediction.explanation_text}
                        </p>
                      )}

                      {prediction.explanation_evidence && (
                        <div className="mt-4 grid grid-cols-2 gap-3">
                          <div className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
                            <p className="text-xs text-slate-500">
                              Supporting influence
                            </p>

                            <p className="mt-1 text-sm font-medium">
                              {(
                                prediction.explanation_evidence
                                  .max_positive_influence * 100
                              ).toFixed(2)}
                              %
                            </p>
                          </div>

                          <div className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
                            <p className="text-xs text-slate-500">
                              Opposing influence
                            </p>

                            <p className="mt-1 text-sm font-medium">
                              {(
                                Math.abs(
                                  prediction.explanation_evidence
                                    .max_negative_influence
                                ) * 100
                              ).toFixed(2)}
                              %
                            </p>
                          </div>
                        </div>
                      )}

                      {prediction.explanation_method && (
                        <p className="mt-3 text-[11px] text-slate-600">
                          Method: {prediction.explanation_method}
                        </p>
                      )}
                    </div>
                  )}

                  <p className="mt-5 text-xs leading-5 text-slate-500">
                    This is a statistical assessment.
                    It may be wrong and should not be
                    treated as proof of image origin.
                  </p>
                </>
              ) : (
                <div>
                  <p className="text-xs uppercase tracking-[0.2em] text-slate-500">
                    Analysis
                  </p>

                  <p className="mt-3 text-sm leading-6 text-slate-500">
                    Upload an image and click
                    “Analyze Image” to see the
                    detector's assessment.
                  </p>
                </div>
              )}
            </div>
          </div>
        </section>

        <section
          className="evaluation-section"
          aria-labelledby="evaluation-title"
        >
          <div className="evaluation-heading">
            <div>
              <p className="section-label">04 / Evaluation</p>
              <h2 id="evaluation-title">Generalization snapshot</h2>
            </div>
            <div className="evaluation-badge">Internal · pseudo-unseen</div>
          </div>

          <div className="evaluation-callout">
            <div>
              <p className="evaluation-kicker">
                Held-out generator used for internal testing
              </p>
              <strong>VQDM</strong>
            </div>
            <p>
              These results come from SignalScope&apos;s internal
              pseudo-unseen split. They are not the official organizer
              held-out test score.
            </p>
          </div>

          <div className="evaluation-metrics">
            <article className="evaluation-metric evaluation-metric-primary">
              <span>ROC-AUC</span>
              <strong>0.728</strong>
              <small>Primary generalization metric</small>
            </article>
            <article className="evaluation-metric">
              <span>Macro-F1</span>
              <strong>0.511</strong>
              <small>Frozen validation threshold</small>
            </article>
            <article className="evaluation-metric">
              <span>Accuracy</span>
              <strong>57.4%</strong>
              <small>1,000-image pseudo-unseen set</small>
            </article>
            <article className="evaluation-metric">
              <span>FPR</span>
              <strong>6.6%</strong>
              <small>Real images falsely flagged</small>
            </article>
          </div>

          <div className="evaluation-details">
            <article className="eval-card">
              <div className="eval-card-heading">
                <div>
                  <p className="section-label">Decision behavior</p>
                  <h3>Confusion matrix</h3>
                </div>
                <span className="eval-card-meta">threshold 64.69%</span>
              </div>

              <div
                className="confusion-matrix"
                role="table"
                aria-label="Confusion matrix for internal pseudo-unseen VQDM evaluation"
              >
                <div className="matrix-corner" role="columnheader">&nbsp;</div>
                <div className="matrix-axis" role="columnheader">Pred. real</div>
                <div className="matrix-axis" role="columnheader">Pred. AI</div>

                <div className="matrix-axis matrix-side" role="rowheader">Actual real</div>
                <div className="matrix-cell matrix-good">
                  <strong>467</strong>
                  <span>True negative</span>
                </div>
                <div className="matrix-cell matrix-warn">
                  <strong>33</strong>
                  <span>False positive</span>
                </div>

                <div className="matrix-axis matrix-side" role="rowheader">Actual AI</div>
                <div className="matrix-cell matrix-soft">
                  <strong>393</strong>
                  <span>False negative</span>
                </div>
                <div className="matrix-cell matrix-good">
                  <strong>107</strong>
                  <span>True positive</span>
                </div>
              </div>
            </article>

            <article className="eval-card">
              <div className="eval-card-heading">
                <div>
                  <p className="section-label">Evaluation protocol</p>
                  <h3>Generalization-first split</h3>
                </div>
              </div>

              <dl className="protocol-list">
                <div><dt>Training</dt><dd>22,000 images</dd></div>
                <div><dt>Validation</dt><dd>16,000 images</dd></div>
                <div><dt>Pseudo-unseen</dt><dd>1,000 VQDM images</dd></div>
                <div><dt>Calibration</dt><dd>Validation only</dd></div>
              </dl>

              <p className="protocol-note">
                The unseen generator is kept outside model training and
                calibration so the internal score measures transfer to a
                generator family the model did not see during training.
              </p>
            </article>
          </div>
        </section>

        <footer className="border-t border-white/10 pt-6 text-xs text-slate-600">
          SignalScope · Likelihood-based AI image
          detection
        </footer>
      </div>
    </main>
  );
}
